project:
  type: website

website:
  title: "LitRecs"
  page-navigation: true
  reader-mode: true  
  favicon: "src/images/LitRecs.png"
  navbar:
    logo: "src/images/LitRecs.png"
    logo-alt: "LitRecs Logo"
    left:
      - href: index.qmd
        text: Home
      - href: getting-started.qmd
        text: Get Started
      - href: guides/index.qmd
        text: Guide
    right:
      - icon: github
        href: https://github.com/unfresh25/LitRecs/tree/quarto-notebook
  
  sidebar: 
    - id: guides
      title: Guides
      collapse-level: 1
      contents:
        - text: Overview
          href: guides/index.qmd
        - text: OpenLibrary API
          href: guides/extracting-data.qmd
        - text: Search Recommendations
          href: guides/search-recommendations.qmd

  page-footer:
    border: true
    left: "Made by Jorge Borja, MsC."
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/jorgeborjas25/
      - icon: github
        href: https://github.com/unfresh25/

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    toc-title: ""
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    lang: en
    mainfont: "Roboto"
    link-external-newwindow: true
    link-external-icon: true
    highlight-style: github

jupyter: litrecs_env
